server:
  port: 9527

spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启注册中心动态路由，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
          uri: lb://cloud-payment-service        #匹配后提供服务的路由地址-动态路由
          predicates:
            - Path=/payment/getPaymentById/**          #断言，路径相匹配的进行路由

eureka:
  client:
    # 把自己注册到注册中心
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # 注册的地址
      defaultZone: http://localhost:7001/eureka/