server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  instance:
    # 注册中心地址
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7001/eureka/